/**
 * Built-in Theme Packages — complete manifest data for the shipped theme roster.
 *
 * Phase 82 keeps `BUILTIN_THEMES` as the single built-in source of truth while
 * exposing explicit browser metadata (`coverage`, `preview`, `visualSignature`)
 * and the shared install/apply shape (`ui`, `tokens`, `widgetStyles`, `screens`).
 *
 * @module editor/builtinThemes
 */

import { FULL_THEME_COVERAGE_KEYS } from '../shared/themePackageContract.js';

function clone(value) {
  return JSON.parse(JSON.stringify(value ?? {}));
}

function cloneTitleScreen(value) {
  const titleScreen = value && typeof value === 'object' ? value : {};
  return {
    background: titleScreen.background ?? null,
    elements: Array.isArray(titleScreen.elements)
      ? titleScreen.elements.map(element => ({ ...(element ?? {}) }))
      : [],
  };
}

function createBuiltinTheme({
  id,
  name,
  description,
  primaryColor,
  preview,
  visualSignature,
  ui,
} = {}) {
  const normalizedUi = {
    theme: clone(ui?.theme),
    widgetStyles: clone(ui?.widgetStyles),
    dialogueBox: clone(ui?.dialogueBox),
    saveLoadScreen: clone(ui?.saveLoadScreen),
    backlogScreen: clone(ui?.backlogScreen),
    gameMenu: clone(ui?.gameMenu),
    settingsScreen: clone(ui?.settingsScreen),
    titleScreen: cloneTitleScreen(ui?.titleScreen),
  };

  return {
    id,
    name,
    description,
    primaryColor,
    coverage: [...FULL_THEME_COVERAGE_KEYS],
    preview: { ...preview },
    visualSignature: {
      ...visualSignature,
      requiredTells: { ...(visualSignature?.requiredTells ?? {}) },
    },
    ui: normalizedUi,
    tokens: { ...(normalizedUi.theme?.tokens ?? {}) },
    colorRecipe: normalizedUi.theme?.colorRecipe ? { ...normalizedUi.theme.colorRecipe } : undefined,
    widgetStyles: clone(normalizedUi.widgetStyles),
    screens: {
      saveLoadScreen: clone(normalizedUi.saveLoadScreen),
      backlogScreen: clone(normalizedUi.backlogScreen),
      gameMenu: clone(normalizedUi.gameMenu),
      settingsScreen: clone(normalizedUi.settingsScreen),
      titleScreen: cloneTitleScreen(normalizedUi.titleScreen),
    },
  };
}

export const BUILTIN_THEMES = [
  createBuiltinTheme({
    id: 'default',
    name: '默认',
    description: '打磨完成的中性出厂基线，以抛光石墨面板统一标题、对话与主要界面。',
    primaryColor: '#7D8AA6',
    preview: {
      mode: 'asset',
      src: '/builtin-themes/default/preview.svg',
      background: '#151A22',
      accent: '#B9C4DA',
      text: '默认',
      initials: '默认',
    },
    visualSignature: {
      materialLanguage: '磨砂石墨面板、缎面冷灰描边与低饱和蓝灰高光',
      contourLanguage: '克制的圆角矩形、稳定横向条带与均匀留白构成 polished neutral baseline',
      styleDirection: 'polished neutral baseline',
      requiredTells: {
        titleScreen: '标题界面以石墨幕布、金属字标和双按钮底座组成可靠出厂入口',
        dialogueBox: '对话框使用半透明石墨层与浅色名牌条保持稳健可读性',
        buttonFamily: '按钮族维持统一的灰蓝高亮、细描边和 8px 圆角',
        majorScreenChrome: '主要界面共用深石墨 chrome 底板、亮边线和克制分栏条',
      },
    },
    ui: {
      theme: {
        colorRecipe: { primary: '#7D8AA6', accent: '#A7B4CF', mode: 'dark' },
        tokens: {
          primary: 'rgba(133, 147, 173, 0.94)',
          accent: 'rgba(185, 196, 218, 0.30)',
          text: 'rgba(239, 243, 249, 0.94)',
          textHeading: 'rgba(250, 252, 255, 0.96)',
          textSecondary: 'rgba(188, 198, 217, 0.78)',
          dialogueBg: 'linear-gradient(to top, rgba(12, 15, 20, 0.96) 0%, rgba(15, 19, 25, 0.90) 70%, rgba(15, 19, 25, 0.72) 100%)',
          panelBg: 'rgba(17, 22, 30, 0.94)',
          menuBg: 'rgba(12, 15, 20, 0.74)',
          cardBg: 'rgba(33, 40, 53, 0.74)',
          btnBg: 'rgba(92, 105, 128, 0.64)',
          btnHoverBg: 'rgba(124, 142, 171, 0.82)',
          shadow: 'rgba(4, 7, 11, 0.38)',
        },
      },
      widgetStyles: {
        tab: {
          activeColor: 'rgba(133, 147, 173, 0.94)',
          inactiveColor: 'rgba(185, 196, 218, 0.16)',
          activeTextColor: '#FFFFFF',
          inactiveTextColor: 'rgba(239, 243, 249, 0.66)',
        },
        toggle: {
          style: 'pill',
          onColor: 'rgba(133, 147, 173, 0.94)',
          offColor: 'rgba(185, 196, 218, 0.18)',
          thumbColor: '#FFFFFF',
        },
        slider: {
          trackColor: 'rgba(185, 196, 218, 0.20)',
          fillColor: 'rgba(133, 147, 173, 0.90)',
          thumbColor: '#FFFFFF',
          thumbStyle: 'capsule',
        },
        panel: {
          background: 'rgba(17, 22, 30, 0.90)',
          borderRadius: 10,
          border: '1px solid rgba(185, 196, 218, 0.20)',
          backdropBlur: 12,
        },
        button: {
          background: 'rgba(92, 105, 128, 0.64)',
          hoverBackground: 'rgba(124, 142, 171, 0.82)',
          activeBackground: 'rgba(155, 169, 193, 0.90)',
          textColor: 'rgba(239, 243, 249, 0.94)',
          borderRadius: 8,
          border: '1px solid rgba(185, 196, 218, 0.24)',
        },
      },
      dialogueBox: {
        layout: 'lower-third',
        nameplateStyle: 'polished-plaque',
        nameplateBackgroundImage: 'ui/themes/default/dialogue/nameplate.svg',
        background: 'rgba(12, 15, 20, 0.92)',
        border: '1px solid rgba(185, 196, 218, 0.20)',
        shadow: '0 16px 40px rgba(4, 7, 11, 0.34)',
        decorations: [
          {
            src: 'ui/themes/default/dialogue/nameplate.svg',
            x: 72,
            y: 18,
            width: 220,
            height: 58,
          },
        ],
      },
      saveLoadScreen: {
        header: {
          title: '存档 / 读档',
          accentBarColor: 'rgba(133, 147, 173, 0.94)',
        },
        slot: {
          background: 'rgba(33, 40, 53, 0.76)',
          borderRadius: 10,
          border: '1px solid rgba(185, 196, 218, 0.18)',
        },
        chrome: {
          backgroundColor: 'rgba(17, 22, 30, 0.86)',
          backgroundImage: 'ui/themes/default/screens/chrome.svg',
          edgeGlow: 'rgba(185, 196, 218, 0.18)',
        },
      },
      backlogScreen: {
        header: {
          title: '回看记录',
          accentBarColor: 'rgba(133, 147, 173, 0.94)',
        },
        entry: {
          speakerColor: 'rgba(239, 243, 249, 0.90)',
          hoverBackground: 'rgba(92, 105, 128, 0.24)',
        },
        chrome: {
          backgroundColor: 'rgba(17, 22, 30, 0.86)',
          backgroundImage: 'ui/themes/default/screens/chrome.svg',
          dividerColor: 'rgba(185, 196, 218, 0.18)',
        },
      },
      gameMenu: {
        background: 'rgba(12, 15, 20, 0.78)',
        borderRadius: 12,
        backdropBlur: 16,
        buttons: {
          save: { label: '保存', icon: '💾' },
          load: { label: '读取', icon: '📂' },
          backlog: { label: '回看', icon: '📝' },
          settings: { label: '设置', icon: '⚙️' },
        },
        chrome: {
          backgroundColor: 'rgba(17, 22, 30, 0.88)',
          backgroundImage: 'ui/themes/default/screens/chrome.svg',
          edgeGlow: 'rgba(185, 196, 218, 0.18)',
        },
      },
      settingsScreen: {
        header: {
          title: { text: '系统设定', color: 'rgba(250, 252, 255, 0.96)' },
          subtitle: '默认基线 · 石墨中性系统',
        },
        tabBar: {
          position: 'left',
          width: 180,
          background: 'rgba(33, 40, 53, 0.68)',
          tabs: [
            { label: '音频', icon: '🔊' },
            { label: '显示', icon: '🖥️' },
            { label: '文字', icon: '📝' },
          ],
        },
        footer: {
          height: 60,
          buttons: [
            { text: '恢复默认', action: 'reset', x: 1030, y: 14 },
          ],
        },
        chrome: {
          backgroundColor: 'rgba(17, 22, 30, 0.90)',
          backgroundImage: 'ui/themes/default/screens/chrome.svg',
          border: '1px solid rgba(185, 196, 218, 0.20)',
        },
      },
      titleScreen: {
        background: 'ui/themes/default/title/background.svg',
        elements: [
          {
            type: 'image',
            src: 'ui/themes/default/title/mark.svg',
            x: 640,
            y: 182,
            anchor: 'center',
            width: 436,
            height: 178,
          },
          {
            type: 'text',
            content: 'DEFAULT SYSTEM',
            x: 640,
            y: 286,
            anchor: 'center',
            fontSize: 20,
            fontFamily: "'Segoe UI', sans-serif",
            color: 'rgba(223, 231, 244, 0.82)',
            letterSpacing: 6,
            textShadow: '0 8px 22px rgba(4, 7, 11, 0.36)',
          },
          {
            type: 'button',
            text: '开始',
            action: 'start',
            x: 640,
            y: 404,
            anchor: 'center',
            width: 236,
            height: 54,
            fontSize: 20,
            fontFamily: "'Segoe UI', sans-serif",
            color: 'rgba(239, 243, 249, 0.94)',
            backgroundColor: 'rgba(92, 105, 128, 0.82)',
            hoverColor: 'rgba(124, 142, 171, 0.90)',
            borderRadius: 8,
            border: '1px solid rgba(185, 196, 218, 0.30)',
          },
          {
            type: 'button',
            text: '设置',
            action: 'settings',
            x: 640,
            y: 474,
            anchor: 'center',
            width: 236,
            height: 54,
            fontSize: 20,
            fontFamily: "'Segoe UI', sans-serif",
            color: 'rgba(239, 243, 249, 0.92)',
            backgroundColor: 'rgba(48, 56, 70, 0.76)',
            hoverColor: 'rgba(91, 107, 132, 0.86)',
            borderRadius: 8,
            border: '1px solid rgba(185, 196, 218, 0.24)',
          },
        ],
      },
    },
  }),
  createBuiltinTheme({
    id: 'wafuu',
    name: '和风',
    description: '日式温暖色调，织物与木纹感面板，作为 golden baseline 保持完整交付。',
    primaryColor: '#C8A882',
    preview: {
      mode: 'asset',
      src: '/builtin-themes/wafuu/preview.svg',
      background: '#2C1D18',
      accent: '#C98683',
      text: '和风',
      initials: '和风',
    },
    visualSignature: {
      materialLanguage: '漆木、和纸与温暖铜色描边的日式器物语言',
      contourLanguage: '细窄边框、横向纹样与留白分层形成静谧轮廓',
      styleDirection: 'warm ceremonial Japanese baseline',
      requiredTells: {
        titleScreen: '标题界面必须保留淡金文字与木色按钮构成的安静仪式感',
        dialogueBox: '对话框需要深色半透明底与织物感名牌层次',
        buttonFamily: '按钮族必须统一为温润木色块面与铜金描边',
        majorScreenChrome: '主要界面 chrome 需要延续深木底与暖金分割线',
      },
    },
    ui: {
      theme: {
        colorRecipe: { primary: '#C98683', accent: '#C19D71', mode: 'dark' },
        tokens: {
          primary: 'rgba(201, 134, 131, 0.90)',
          accent: 'rgba(193, 157, 113, 0.25)',
          text: 'rgba(244, 235, 226, 0.92)',
          textHeading: 'rgba(235, 220, 203, 0.85)',
          textSecondary: 'rgba(206, 186, 163, 0.75)',
          dialogueBg: 'linear-gradient(to top, rgba(20, 12, 10, 0.92) 0%, rgba(20, 12, 10, 0.88) 70%, rgba(20, 12, 10, 0.75) 100%)',
          panelBg: 'rgba(18, 12, 10, 0.95)',
          menuBg: 'rgba(14, 8, 6, 0.70)',
          cardBg: 'rgba(38, 24, 18, 0.60)',
          btnBg: 'rgba(89, 56, 38, 0.60)',
          btnHoverBg: 'rgba(138, 80, 40, 0.70)',
          shadow: 'rgba(106, 50, 47, 0.30)',
          fontDisplay: "'Noto Serif SC', serif",
        },
      },
      widgetStyles: {
        tab: {
          shape: 'ribbon',
          activeColor: 'rgba(201, 134, 131, 0.85)',
          inactiveColor: 'rgba(193, 157, 113, 0.15)',
          activeTextColor: '#fff',
          inactiveTextColor: 'rgba(244, 235, 226, 0.6)',
        },
        toggle: {
          style: 'pill',
          onColor: 'rgba(201, 134, 131, 0.85)',
          offColor: 'rgba(193, 157, 113, 0.15)',
          thumbColor: '#fff',
        },
        slider: {
          trackColor: 'rgba(193, 157, 113, 0.15)',
          fillColor: 'rgba(201, 134, 131, 0.8)',
          thumbColor: '#fff',
          thumbStyle: 'circle',
        },
        panel: {
          background: 'rgba(18, 12, 10, 0.85)',
          borderRadius: 4,
          border: '1px solid rgba(193, 157, 113, 0.2)',
          backdropBlur: 8,
        },
        button: {
          background: 'rgba(89, 56, 38, 0.6)',
          hoverBackground: 'rgba(138, 80, 40, 0.7)',
          activeBackground: 'rgba(160, 90, 45, 0.8)',
          textColor: 'rgba(244, 235, 226, 0.9)',
          borderRadius: 4,
          border: '1px solid rgba(193, 157, 113, 0.2)',
        },
      },
      dialogueBox: {
        layout: 'lower-third',
        nameplateStyle: 'woven-plaque',
        background: 'rgba(20, 12, 10, 0.90)',
        border: '1px solid rgba(193, 157, 113, 0.22)',
        shadow: '0 10px 30px rgba(20, 12, 10, 0.32)',
      },
      saveLoadScreen: {
        header: {
          title: '存档 / 读档',
          saveTitleColor: 'rgba(201, 134, 131, 0.9)',
          loadTitleColor: 'rgba(193, 157, 113, 0.9)',
        },
        slot: {
          borderRadius: 4,
          border: '1px solid rgba(193, 157, 113, 0.15)',
          background: 'rgba(38, 24, 18, 0.60)',
        },
        pagination: {
          activeColor: 'rgba(201, 134, 131, 0.9)',
        },
        chrome: {
          backgroundColor: 'rgba(18, 12, 10, 0.84)',
          edgeGlow: 'rgba(193, 157, 113, 0.18)',
        },
      },
      backlogScreen: {
        header: { title: '回 想' },
        entry: {
          speakerColor: 'rgba(201, 134, 131, 0.9)',
          hoverBackground: 'rgba(89, 56, 38, 0.2)',
        },
        chrome: {
          backgroundColor: 'rgba(18, 12, 10, 0.84)',
          dividerColor: 'rgba(193, 157, 113, 0.18)',
        },
      },
      gameMenu: {
        background: 'rgba(18, 12, 10, 0.85)',
        borderRadius: 4,
        backdropBlur: 8,
        buttons: {
          save: { label: '保存', icon: '💾' },
          load: { label: '读取', icon: '📂' },
          backlog: { label: '回看', icon: '📝' },
          settings: { label: '设置', icon: '⚙️' },
        },
        chrome: {
          backgroundColor: 'rgba(18, 12, 10, 0.84)',
          edgeGlow: 'rgba(193, 157, 113, 0.18)',
        },
      },
      settingsScreen: {
        header: {
          title: { text: '系统设定', color: 'rgba(244, 235, 226, 0.9)' },
          subtitle: '和风 · 温暖木色系统',
        },
        tabBar: {
          position: 'left',
          width: 180,
          background: 'rgba(38, 24, 18, 0.5)',
          tabs: [
            { label: '音声', icon: '🔊' },
            { label: '画面', icon: '🖥️' },
            { label: '文字', icon: '📝' },
          ],
        },
        footer: {
          height: 60,
          buttons: [
            { text: '恢复默认', action: 'reset', x: 1030, y: 14 },
          ],
        },
        chrome: {
          backgroundColor: 'rgba(18, 12, 10, 0.88)',
          border: '1px solid rgba(193, 157, 113, 0.18)',
        },
      },
      titleScreen: {
        background: null,
        elements: [
          {
            type: 'text',
            content: '物语',
            x: 640,
            y: 150,
            anchor: 'center',
            fontSize: 52,
            fontFamily: "'Noto Serif SC', serif",
            color: 'rgba(244, 235, 226, 0.92)',
            letterSpacing: 12,
            textShadow: '0 6px 24px rgba(20, 12, 10, 0.45)',
          },
          {
            type: 'button',
            text: '开始',
            action: 'start',
            x: 640,
            y: 360,
            anchor: 'center',
            width: 220,
            height: 52,
            fontSize: 20,
            fontFamily: "'Noto Serif SC', serif",
            color: 'rgba(244, 235, 226, 0.92)',
            backgroundColor: 'rgba(89, 56, 38, 0.72)',
            hoverColor: 'rgba(138, 80, 40, 0.82)',
            borderRadius: 6,
            border: '1px solid rgba(193, 157, 113, 0.45)',
          },
          {
            type: 'button',
            text: '设置',
            action: 'settings',
            x: 640,
            y: 430,
            anchor: 'center',
            width: 220,
            height: 52,
            fontSize: 20,
            fontFamily: "'Noto Serif SC', serif",
            color: 'rgba(244, 235, 226, 0.92)',
            backgroundColor: 'rgba(89, 56, 38, 0.58)',
            hoverColor: 'rgba(138, 80, 40, 0.78)',
            borderRadius: 6,
            border: '1px solid rgba(193, 157, 113, 0.35)',
          },
        ],
      },
    },
  }),
  createBuiltinTheme({
    id: 'modern-sky',
    name: '现代天蓝',
    description: '轻盈通透的玻璃卡片主题，以天蓝高光和漂浮分栏统一标题、对话与主要界面。',
    primaryColor: '#4A90D9',
    preview: {
      mode: 'asset',
      src: '/builtin-themes/modern-sky/preview.svg',
      background: '#0C1521',
      accent: '#84CAFF',
      text: '现代天蓝',
      initials: '天蓝',
    },
    visualSignature: {
      materialLanguage: '浅玻璃、雾面亚克力、天蓝边光与稀薄云层高光',
      contourLanguage: 'slim radii、悬浮卡片、细分隔线与通透层叠构成轻盈都市 UI',
      styleDirection: 'airy glass / slim-radii / floating-card direction',
      requiredTells: {
        titleScreen: '标题界面必须读出云层天光、玻璃徽标与漂浮按钮卡片的层次',
        dialogueBox: '对话框要保留冰蓝玻璃名牌和细亮边的浮层感',
        buttonFamily: '按钮族统一使用轻玻璃底、蓝色边光与 slim-radii 轮廓',
        majorScreenChrome: '主要界面 chrome 需要持续出现浮层分栏、柔性光带和天蓝边线',
      },
    },
    ui: {
      theme: {
        colorRecipe: { primary: '#4A90D9', accent: '#DB9B57', mode: 'dark' },
        tokens: {
          primary: 'rgba(92, 176, 247, 0.92)',
          accent: 'rgba(132, 202, 255, 0.30)',
          text: 'rgba(236, 246, 255, 0.95)',
          textHeading: 'rgba(246, 251, 255, 0.98)',
          textSecondary: 'rgba(188, 214, 240, 0.82)',
          dialogueBg: 'linear-gradient(to top, rgba(15, 28, 42, 0.86) 0%, rgba(17, 34, 52, 0.76) 72%, rgba(19, 42, 66, 0.56) 100%)',
          panelBg: 'rgba(14, 26, 38, 0.72)',
          menuBg: 'rgba(11, 24, 36, 0.62)',
          cardBg: 'rgba(24, 48, 72, 0.42)',
          btnBg: 'rgba(39, 94, 148, 0.42)',
          btnHoverBg: 'rgba(74, 143, 217, 0.62)',
          shadow: 'rgba(4, 12, 22, 0.28)',
        },
      },
      widgetStyles: {
        tab: {
          activeColor: 'rgba(92, 176, 247, 0.86)',
          inactiveColor: 'rgba(132, 202, 255, 0.16)',
          activeTextColor: '#FFFFFF',
          inactiveTextColor: 'rgba(236, 246, 255, 0.70)',
        },
        toggle: {
          onColor: 'rgba(92, 176, 247, 0.88)',
          offColor: 'rgba(132, 202, 255, 0.18)',
          thumbColor: '#FFFFFF',
          style: 'pill',
        },
        slider: {
          trackColor: 'rgba(132, 202, 255, 0.20)',
          fillColor: 'rgba(92, 176, 247, 0.84)',
          thumbColor: '#FFFFFF',
          thumbStyle: 'rounded-rect',
        },
        panel: {
          background: 'rgba(16, 32, 48, 0.50)',
          border: '1px solid rgba(132, 202, 255, 0.24)',
          borderRadius: 18,
          backdropBlur: 18,
        },
        button: {
          background: 'rgba(39, 94, 148, 0.44)',
          hoverBackground: 'rgba(74, 143, 217, 0.62)',
          activeBackground: 'rgba(92, 176, 247, 0.82)',
          textColor: 'rgba(236, 246, 255, 0.96)',
          borderRadius: 14,
          border: '1px solid rgba(132, 202, 255, 0.28)',
        },
      },
      dialogueBox: {
        layout: 'floating-card',
        nameplateStyle: 'glass-strip',
        nameplateBackgroundImage: 'ui/themes/modern-sky/dialogue/nameplate.svg',
        background: 'rgba(16, 30, 44, 0.68)',
        border: '1px solid rgba(132, 202, 255, 0.26)',
        shadow: '0 18px 40px rgba(4, 12, 22, 0.30)',
        decorations: [
          {
            src: 'ui/themes/modern-sky/dialogue/nameplate.svg',
            x: 76,
            y: 16,
            width: 236,
            height: 62,
          },
        ],
      },
      saveLoadScreen: {
        header: {
          title: '云端记忆',
          accentBarColor: 'rgba(92, 176, 247, 0.88)',
        },
        slot: {
          background: 'rgba(24, 48, 72, 0.36)',
          borderRadius: 18,
          border: '1px solid rgba(132, 202, 255, 0.20)',
        },
        chrome: {
          backgroundColor: 'rgba(14, 26, 38, 0.54)',
          backgroundImage: 'ui/themes/modern-sky/screens/chrome.svg',
          edgeGlow: 'rgba(92, 176, 247, 0.24)',
        },
      },
      backlogScreen: {
        header: {
          title: '讯息回放',
          accentBarColor: 'rgba(92, 176, 247, 0.88)',
        },
        entry: {
          speakerColor: 'rgba(157, 214, 255, 0.96)',
          hoverBackground: 'rgba(74, 143, 217, 0.18)',
        },
        chrome: {
          backgroundColor: 'rgba(14, 26, 38, 0.58)',
          backgroundImage: 'ui/themes/modern-sky/screens/chrome.svg',
          dividerColor: 'rgba(132, 202, 255, 0.18)',
        },
      },
      gameMenu: {
        background: 'rgba(11, 24, 36, 0.62)',
        borderRadius: 18,
        backdropBlur: 20,
        buttons: {
          save: { label: '保存', icon: '💾' },
          load: { label: '读取', icon: '📁' },
          backlog: { label: '回放', icon: '🧾' },
          settings: { label: '系统', icon: '⚙️' },
        },
        chrome: {
          backgroundColor: 'rgba(14, 26, 38, 0.56)',
          backgroundImage: 'ui/themes/modern-sky/screens/chrome.svg',
          edgeGlow: 'rgba(92, 176, 247, 0.22)',
        },
      },
      settingsScreen: {
        header: {
          title: { text: '系统调校', color: 'rgba(236, 246, 255, 0.96)' },
          subtitle: '现代天蓝 · 双栏浮层玻璃布局',
        },
        tabBar: {
          position: 'left',
          width: 196,
          background: 'rgba(24, 48, 72, 0.36)',
          tabs: [
            { label: '音频', icon: '🔊' },
            { label: '显示', icon: '🖥️' },
            { label: '文字', icon: '📝' },
          ],
        },
        contentArea: {
          columns: 2,
          itemStyle: {
            showDividers: true,
            alternateBackground: true,
          },
        },
        footer: {
          height: 60,
          buttons: [
            { text: '同步推荐值', action: 'reset', x: 980, y: 14 },
          ],
        },
        chrome: {
          backgroundColor: 'rgba(14, 26, 38, 0.54)',
          backgroundImage: 'ui/themes/modern-sky/screens/chrome.svg',
          border: '1px solid rgba(132, 202, 255, 0.22)',
        },
      },
      titleScreen: {
        background: 'ui/themes/modern-sky/title/background.svg',
        elements: [
          {
            type: 'image',
            src: 'ui/themes/modern-sky/title/mark.svg',
            x: 640,
            y: 196,
            anchor: 'center',
            width: 468,
            height: 190,
          },
          {
            type: 'text',
            content: 'SKYLINE GLASS',
            x: 640,
            y: 292,
            anchor: 'center',
            fontSize: 18,
            fontFamily: "'Segoe UI', sans-serif",
            color: 'rgba(214, 238, 255, 0.88)',
            letterSpacing: 7,
            textShadow: '0 10px 30px rgba(4, 12, 22, 0.34)',
          },
          {
            type: 'button',
            text: '开始',
            action: 'start',
            x: 640,
            y: 406,
            anchor: 'center',
            width: 236,
            height: 54,
            fontSize: 20,
            fontFamily: "'Segoe UI', sans-serif",
            color: 'rgba(236, 246, 255, 0.96)',
            backgroundColor: 'rgba(39, 94, 148, 0.50)',
            hoverColor: 'rgba(74, 143, 217, 0.72)',
            borderRadius: 14,
            border: '1px solid rgba(132, 202, 255, 0.28)',
          },
          {
            type: 'button',
            text: '设置',
            action: 'settings',
            x: 640,
            y: 476,
            anchor: 'center',
            width: 236,
            height: 54,
            fontSize: 20,
            fontFamily: "'Segoe UI', sans-serif",
            color: 'rgba(236, 246, 255, 0.94)',
            backgroundColor: 'rgba(20, 44, 68, 0.46)',
            hoverColor: 'rgba(62, 120, 179, 0.68)',
            borderRadius: 14,
            border: '1px solid rgba(132, 202, 255, 0.24)',
          },
        ],
      },
    },
  }),
  createBuiltinTheme({
    id: 'fantasy-dark',
    name: '暗黑幻想',
    description: '深紫与古金的奇幻宫廷界面，强调纹章、饰边与戏剧化层次。',
    primaryColor: '#9B6EC8',
    preview: {
      mode: 'asset',
      src: '/builtin-themes/fantasy-dark/preview.svg',
      background: '#160E1F',
      accent: '#D7AF5F',
      text: '暗黑幻想',
      initials: '幻想',
    },
    visualSignature: {
      materialLanguage: '深紫天鹅绒、熏金金属与旧羊皮纸共同组成宫廷奇幻材质',
      contourLanguage: '尖拱、盾徽、菱形徽章与多重包边形成带仪式感的奇幻轮廓',
      styleDirection: 'ornate dark-fantasy ceremonial language',
      requiredTells: {
        titleScreen: '标题界面必须出现 crest 式字标、紫黑幕布与古金徽章高光的仪式感',
        dialogueBox: '对话框应保留羊皮纸徽章名牌与绒面深底的宫廷宣告感',
        buttonFamily: '按钮族需要统一为古金边深紫底座，并读出尖拱或纹章化细节',
        majorScreenChrome: '主要界面 chrome 必须持续有古金分割、盾徽角饰与祭坛式框景',
      },
    },
    ui: {
      theme: {
        colorRecipe: { primary: '#9B6EC8', accent: '#D7AF5F', mode: 'dark' },
        tokens: {
          primary: 'rgba(155, 110, 200, 0.90)',
          accent: 'rgba(215, 175, 95, 0.25)',
          text: 'rgba(245, 236, 220, 0.94)',
          textHeading: 'rgba(255, 244, 224, 0.96)',
          textSecondary: 'rgba(217, 198, 160, 0.78)',
          dialogueBg: 'linear-gradient(to top, rgba(12, 8, 18, 0.92) 0%, rgba(12, 8, 18, 0.88) 70%, rgba(12, 8, 18, 0.75) 100%)',
          panelBg: 'rgba(14, 10, 20, 0.95)',
          menuBg: 'rgba(12, 8, 18, 0.72)',
          cardBg: 'rgba(31, 20, 44, 0.66)',
          btnBg: 'rgba(60, 40, 80, 0.60)',
          btnHoverBg: 'rgba(80, 55, 110, 0.70)',
          shadow: 'rgba(5, 2, 8, 0.34)',
        },
      },
      widgetStyles: {
        tab: {
          activeColor: 'rgba(155, 110, 200, 0.85)',
          inactiveColor: 'rgba(215, 175, 95, 0.12)',
          activeTextColor: '#FFF5E3',
          inactiveTextColor: 'rgba(245, 236, 220, 0.64)',
        },
        toggle: {
          onColor: 'rgba(155, 110, 200, 0.85)',
          offColor: 'rgba(215, 175, 95, 0.14)',
          thumbColor: '#FFF5E3',
          style: 'pill',
        },
        slider: {
          trackColor: 'rgba(215, 175, 95, 0.14)',
          fillColor: 'rgba(155, 110, 200, 0.8)',
          thumbColor: '#FFF5E3',
          thumbStyle: 'gem',
        },
        panel: {
          background: 'rgba(14, 10, 20, 0.88)',
          border: '1px solid rgba(215, 175, 95, 0.22)',
          borderRadius: 10,
          backdropBlur: 10,
        },
        button: {
          background: 'rgba(60, 40, 80, 0.6)',
          hoverBackground: 'rgba(80, 55, 110, 0.7)',
          activeBackground: 'rgba(110, 78, 145, 0.82)',
          textColor: 'rgba(245, 236, 220, 0.94)',
          borderRadius: 8,
          border: '1px solid rgba(215, 175, 95, 0.24)',
        },
      },
      dialogueBox: {
        layout: 'crest-panel',
        nameplateStyle: 'sigil-plaque',
        nameplateBackgroundImage: 'ui/themes/fantasy-dark/dialogue/nameplate.svg',
        background: 'rgba(12, 8, 18, 0.90)',
        border: '1px solid rgba(215, 175, 95, 0.24)',
        shadow: '0 18px 40px rgba(5, 2, 8, 0.36)',
        decorations: [
          {
            src: 'ui/themes/fantasy-dark/dialogue/nameplate.svg',
            x: 68,
            y: 14,
            width: 252,
            height: 72,
          },
        ],
      },
      saveLoadScreen: {
        header: {
          title: '圣典档案',
          accentBarColor: 'rgba(215, 175, 95, 0.88)',
        },
        slot: {
          background: 'rgba(31, 20, 44, 0.68)',
          borderRadius: 10,
          border: '1px solid rgba(215, 175, 95, 0.18)',
        },
        chrome: {
          backgroundColor: 'rgba(14, 10, 20, 0.84)',
          backgroundImage: 'ui/themes/fantasy-dark/screens/chrome.svg',
          edgeGlow: 'rgba(215, 175, 95, 0.20)',
        },
      },
      backlogScreen: {
        header: {
          title: '编年回响',
          accentBarColor: 'rgba(215, 175, 95, 0.88)',
        },
        entry: {
          speakerColor: 'rgba(255, 223, 154, 0.92)',
          hoverBackground: 'rgba(80, 55, 110, 0.18)',
        },
        chrome: {
          backgroundColor: 'rgba(14, 10, 20, 0.84)',
          backgroundImage: 'ui/themes/fantasy-dark/screens/chrome.svg',
          dividerColor: 'rgba(215, 175, 95, 0.18)',
        },
      },
      gameMenu: {
        background: 'rgba(12, 8, 18, 0.74)',
        borderRadius: 12,
        backdropBlur: 12,
        buttons: {
          save: { label: '保存', icon: '🕯️' },
          load: { label: '读取', icon: '📜' },
          backlog: { label: '编年', icon: '🗒️' },
          settings: { label: '秘仪', icon: '⚙️' },
        },
        chrome: {
          backgroundColor: 'rgba(14, 10, 20, 0.84)',
          backgroundImage: 'ui/themes/fantasy-dark/screens/chrome.svg',
          edgeGlow: 'rgba(215, 175, 95, 0.20)',
        },
      },
      settingsScreen: {
        header: {
          title: { text: '系统设定', color: 'rgba(245, 236, 220, 0.94)' },
          subtitle: '暗黑幻想 · 宫廷纹章布局',
        },
        tabBar: {
          position: 'left',
          width: 188,
          background: 'rgba(31, 20, 44, 0.56)',
          tabs: [
            { label: '声音', icon: '🔉' },
            { label: '画面', icon: '🎨' },
            { label: '文字', icon: '✒️' },
          ],
        },
        footer: {
          height: 60,
          buttons: [
            { text: '恢复仪式默认', action: 'reset', x: 948, y: 14 },
          ],
        },
        chrome: {
          backgroundColor: 'rgba(14, 10, 20, 0.86)',
          backgroundImage: 'ui/themes/fantasy-dark/screens/chrome.svg',
          border: '1px solid rgba(215, 175, 95, 0.20)',
        },
      },
      titleScreen: {
        background: 'ui/themes/fantasy-dark/title/background.svg',
        elements: [
          {
            type: 'image',
            src: 'ui/themes/fantasy-dark/title/mark.svg',
            x: 640,
            y: 182,
            anchor: 'center',
            width: 520,
            height: 236,
          },
          {
            type: 'text',
            content: 'ECLIPSE COURT',
            x: 640,
            y: 308,
            anchor: 'center',
            fontSize: 22,
            fontFamily: "'Cinzel', serif",
            color: 'rgba(255, 244, 224, 0.96)',
            letterSpacing: 10,
            textShadow: '0 10px 28px rgba(5, 2, 8, 0.42)',
          },
          {
            type: 'button',
            text: '开始',
            action: 'start',
            x: 640,
            y: 392,
            anchor: 'center',
            width: 244,
            height: 56,
            fontSize: 20,
            fontFamily: "'Cinzel', serif",
            color: 'rgba(245, 236, 220, 0.94)',
            backgroundColor: 'rgba(60, 40, 80, 0.78)',
            hoverColor: 'rgba(110, 78, 145, 0.88)',
            borderRadius: 6,
            border: '1px solid rgba(215, 175, 95, 0.30)',
          },
          {
            type: 'button',
            text: '设置',
            action: 'settings',
            x: 640,
            y: 466,
            anchor: 'center',
            width: 244,
            height: 56,
            fontSize: 20,
            fontFamily: "'Cinzel', serif",
            color: 'rgba(245, 236, 220, 0.94)',
            backgroundColor: 'rgba(31, 20, 44, 0.76)',
            hoverColor: 'rgba(80, 55, 110, 0.86)',
            borderRadius: 6,
            border: '1px solid rgba(215, 175, 95, 0.26)',
          },
        ],
      },
    },
  }),
  createBuiltinTheme({
    id: 'minimal-white',
    name: '极简白',
    description: '明亮纸页与墨色细线的编辑主题，以留白、字号层级和安静分隔建立版式感。',
    primaryColor: '#879E90',
    preview: {
      mode: 'asset',
      src: '/builtin-themes/minimal-white/preview.svg',
      background: '#F6F3EC',
      accent: '#879E90',
      text: '极简白',
      initials: '极简',
    },
    visualSignature: {
      materialLanguage: '暖白纸页、墨色细线与少量鼠尾草灰绿点缀形成杂志式材质',
      contourLanguage: '平边卡片、细规则线、栏位对齐与大留白形成编辑版式轮廓',
      styleDirection: 'bright minimal editorial page language',
      requiredTells: {
        titleScreen: '标题界面必须让字标主导构图，并以纸页背景和细规则线建立版式节奏',
        dialogueBox: '对话框要读出浅纸面底、细线标签与安静页眉的编辑感',
        buttonFamily: '按钮族统一为轻纸卡与墨色字重，辅以极少量灰绿点缀，不可回到厚重深色块面',
        majorScreenChrome: '主要界面 chrome 必须延续纸页底、栏位分隔与杂志页边线节奏',
      },
    },
    ui: {
      theme: {
        colorRecipe: { primary: '#879E90', accent: '#2E342F', mode: 'light' },
        tokens: {
          primary: 'rgba(135, 158, 144, 0.88)',
          accent: 'rgba(46, 52, 47, 0.08)',
          text: 'rgba(35, 36, 35, 0.94)',
          textHeading: 'rgba(24, 25, 24, 0.92)',
          textSecondary: 'rgba(88, 90, 88, 0.72)',
          dialogueBg: 'linear-gradient(to top, rgba(250, 247, 241, 0.96) 0%, rgba(250, 247, 241, 0.92) 70%, rgba(250, 247, 241, 0.84) 100%)',
          panelBg: 'rgba(252, 249, 244, 0.96)',
          menuBg: 'rgba(246, 243, 236, 0.86)',
          cardBg: 'rgba(255, 255, 255, 0.84)',
          btnBg: 'rgba(255, 255, 255, 0.96)',
          btnHoverBg: 'rgba(236, 240, 236, 0.98)',
          shadow: 'rgba(120, 122, 118, 0.12)',
        },
      },
      widgetStyles: {
        tab: {
          activeColor: 'rgba(255, 255, 255, 0.98)',
          inactiveColor: 'rgba(46, 52, 47, 0.05)',
          activeTextColor: 'rgba(24, 25, 24, 0.92)',
          inactiveTextColor: 'rgba(70, 72, 70, 0.66)',
        },
        toggle: {
          onColor: 'rgba(135, 158, 144, 0.88)',
          offColor: 'rgba(46, 52, 47, 0.10)',
          thumbColor: '#FFFFFF',
          style: 'pill',
        },
        slider: {
          trackColor: 'rgba(46, 52, 47, 0.08)',
          fillColor: 'rgba(135, 158, 144, 0.84)',
          thumbColor: '#FFFFFF',
          thumbStyle: 'capsule',
        },
        panel: {
          background: 'rgba(252, 249, 244, 0.96)',
          border: '1px solid rgba(46, 52, 47, 0.10)',
          borderRadius: 4,
          backdropBlur: 0,
        },
        button: {
          background: 'rgba(255, 255, 255, 0.96)',
          hoverBackground: 'rgba(236, 240, 236, 0.98)',
          activeBackground: 'rgba(223, 230, 224, 0.98)',
          textColor: 'rgba(35, 36, 35, 0.94)',
          borderRadius: 4,
          border: '1px solid rgba(46, 52, 47, 0.12)',
        },
      },
      dialogueBox: {
        layout: 'paper-sheet',
        nameplateStyle: 'inline-label',
        nameplateBackgroundImage: 'ui/themes/minimal-white/dialogue/nameplate.svg',
        background: 'rgba(252, 249, 244, 0.96)',
        border: '1px solid rgba(46, 52, 47, 0.10)',
        shadow: '0 10px 24px rgba(120, 122, 118, 0.10)',
        decorations: [
          {
            src: 'ui/themes/minimal-white/dialogue/nameplate.svg',
            x: 72,
            y: 18,
            width: 232,
            height: 60,
          },
        ],
      },
      saveLoadScreen: {
        header: {
          title: '记录',
          accentBarColor: 'rgba(91, 168, 126, 0.84)',
        },
        slot: {
          background: 'rgba(255, 255, 255, 0.92)',
          borderRadius: 12,
          border: '1px solid rgba(91, 168, 126, 0.14)',
        },
        chrome: {
          backgroundColor: 'rgba(250, 247, 241, 0.96)',
          backgroundImage: 'ui/themes/minimal-white/screens/chrome.svg',
          edgeGlow: 'rgba(135, 158, 144, 0.08)',
        },
      },
      backlogScreen: {
        header: {
          title: '对白记录',
          accentBarColor: 'rgba(91, 168, 126, 0.84)',
        },
        entry: {
          speakerColor: 'rgba(60, 120, 86, 0.92)',
          hoverBackground: 'rgba(91, 168, 126, 0.12)',
        },
        chrome: {
          backgroundColor: 'rgba(250, 247, 241, 0.96)',
          backgroundImage: 'ui/themes/minimal-white/screens/chrome.svg',
          dividerColor: 'rgba(46, 52, 47, 0.10)',
        },
      },
      gameMenu: {
        background: 'rgba(246, 243, 236, 0.90)',
        borderRadius: 4,
        backdropBlur: 0,
        buttons: {
          save: { label: '保存', icon: '💾' },
          load: { label: '读取', icon: '📂' },
          backlog: { label: '回看', icon: '📝' },
          settings: { label: '设置', icon: '⚙️' },
        },
        chrome: {
          backgroundColor: 'rgba(250, 247, 241, 0.96)',
          backgroundImage: 'ui/themes/minimal-white/screens/chrome.svg',
          edgeGlow: 'rgba(135, 158, 144, 0.08)',
        },
      },
      settingsScreen: {
        header: {
          title: { text: '系统设定', color: 'rgba(24, 25, 24, 0.92)' },
          subtitle: '极简白 · 明亮版式系统',
        },
        tabBar: {
          position: 'left',
          width: 176,
          background: 'rgba(244, 241, 235, 0.92)',
          tabs: [
            { label: '音频', icon: '🔊' },
            { label: '显示', icon: '🖥️' },
            { label: '文字', icon: '📝' },
          ],
        },
        footer: {
          height: 60,
          buttons: [
            { text: '恢复默认', action: 'reset', x: 1030, y: 14 },
          ],
        },
        chrome: {
          backgroundColor: 'rgba(250, 247, 241, 0.98)',
          backgroundImage: 'ui/themes/minimal-white/screens/chrome.svg',
          border: '1px solid rgba(46, 52, 47, 0.10)',
        },
      },
      titleScreen: {
        background: 'ui/themes/minimal-white/title/background.svg',
        elements: [
          {
            type: 'image',
            src: 'ui/themes/minimal-white/title/mark.svg',
            x: 640,
            y: 184,
            anchor: 'center',
            width: 540,
            height: 210,
          },
          {
            type: 'text',
            content: 'EDITORIAL STORY',
            x: 640,
            y: 292,
            anchor: 'center',
            fontSize: 18,
            fontFamily: "'Segoe UI', sans-serif",
            color: 'rgba(35, 36, 35, 0.78)',
            letterSpacing: 8,
            textShadow: '0 6px 18px rgba(120, 122, 118, 0.08)',
          },
          {
            type: 'button',
            text: '开始',
            action: 'start',
            x: 640,
            y: 388,
            anchor: 'center',
            width: 244,
            height: 54,
            fontSize: 18,
            fontFamily: "'Segoe UI', sans-serif",
            color: 'rgba(24, 25, 24, 0.92)',
            backgroundColor: 'rgba(255, 255, 255, 0.96)',
            hoverColor: 'rgba(236, 240, 236, 0.98)',
            borderRadius: 4,
            border: '1px solid rgba(46, 52, 47, 0.12)',
          },
          {
            type: 'button',
            text: '设置',
            action: 'settings',
            x: 640,
            y: 458,
            anchor: 'center',
            width: 244,
            height: 54,
            fontSize: 18,
            fontFamily: "'Segoe UI', sans-serif",
            color: 'rgba(35, 36, 35, 0.90)',
            backgroundColor: 'rgba(246, 243, 236, 0.98)',
            hoverColor: 'rgba(228, 233, 228, 0.98)',
            borderRadius: 4,
            border: '1px solid rgba(46, 52, 47, 0.10)',
          },
        ],
      },
    },
  }),
  createBuiltinTheme({
    id: 'alchemy-rose',
    name: '炼金蔷薇',
    description: '玫瑰金线饰与烟紫玻璃质感组成的通用视觉小说主题。',
    primaryColor: '#B85D79',
    preview: {
      mode: 'asset',
      src: '/builtin-themes/alchemy-rose/preview.svg',
      background: '#160916',
      accent: '#E7B7BD',
      text: '炼金蔷薇',
      initials: '蔷薇',
    },
    visualSignature: {
      materialLanguage: '烟紫半透明玻璃、玫瑰金金属线饰、细密几何纹样与柔粉高光',
      contourLanguage: '斜切长框、菱形徽章、细线内框和角部花饰构成成熟 VN 视觉层次',
      styleDirection: 'romantic rose-gold premium VN interface',
      requiredTells: {
        titleScreen: '标题界面必须出现玫瑰金字标和烟紫背景光晕',
        dialogueBox: '对话框必须使用玫瑰金九宫格框体、姓名牌和半透明烟紫玻璃底',
        buttonFamily: '按钮族必须统一为斜切长框、粉金高光与青蓝副色选项徽章',
        majorScreenChrome: '主要界面 chrome 必须延续细线框、玫瑰金分割和暗紫玻璃面板',
      },
    },
    ui: {
      theme: {
        colorRecipe: { primary: '#B85D79', accent: '#E7B7BD', mode: 'dark' },
        tokens: {
          primary: 'rgba(184, 93, 121, 0.92)',
          accent: 'rgba(231, 183, 189, 0.30)',
          text: 'rgba(255, 241, 244, 0.94)',
          textHeading: 'rgba(255, 226, 231, 0.98)',
          textSecondary: 'rgba(220, 181, 188, 0.78)',
          dialogueBg: 'linear-gradient(to top, rgba(18, 8, 18, 0.94) 0%, rgba(48, 20, 42, 0.86) 72%, rgba(92, 38, 62, 0.58) 100%)',
          panelBg: 'rgba(20, 9, 19, 0.92)',
          menuBg: 'rgba(12, 6, 14, 0.70)',
          cardBg: 'rgba(58, 24, 48, 0.58)',
          btnBg: 'rgba(76, 32, 58, 0.62)',
          btnHoverBg: 'rgba(138, 63, 96, 0.78)',
          shadow: 'rgba(5, 2, 8, 0.38)',
          fontDisplay: "'Noto Serif SC', Georgia, serif",
          fontBody: "'Noto Serif SC', Georgia, serif",
        },
        nineSlice: {
          dialogueBox: {
            src: 'ui/themes/alchemy-rose/dialogue/frame.svg',
            slice: [36, 36, 36, 36],
            width: [18, 18, 18, 18],
          },
          choiceButton: {
            src: 'ui/themes/alchemy-rose/choices/choice-normal.svg',
            slice: [18, 42, 18, 42],
            width: [10, 24, 10, 24],
            states: {
              hover: { src: 'ui/themes/alchemy-rose/choices/choice-hover.svg' },
              active: { src: 'ui/themes/alchemy-rose/choices/choice-pressed.svg' },
            },
          },
          titleButton: {
            src: 'ui/themes/alchemy-rose/choices/choice-normal.svg',
            slice: [18, 42, 18, 42],
            width: [10, 24, 10, 24],
            states: {
              hover: { src: 'ui/themes/alchemy-rose/choices/choice-hover.svg' },
              active: { src: 'ui/themes/alchemy-rose/choices/choice-pressed.svg' },
            },
          },
          menuPanel: {
            src: 'ui/themes/alchemy-rose/dialogue/frame.svg',
            slice: [36, 36, 36, 36],
            width: [16, 16, 16, 16],
          },
          saveSlot: {
            src: 'ui/themes/alchemy-rose/choices/choice-normal.svg',
            slice: [18, 42, 18, 42],
            width: [8, 18, 8, 18],
          },
          settingsPanel: {
            src: 'ui/themes/alchemy-rose/dialogue/frame.svg',
            slice: [36, 36, 36, 36],
            width: [16, 16, 16, 16],
          },
        },
        choiceBadge: {
          a: 'ui/themes/alchemy-rose/choices/badge-a.svg',
          b: 'ui/themes/alchemy-rose/choices/badge-b.svg',
          c: 'ui/themes/alchemy-rose/choices/badge-c.svg',
        },
        cursor: {
          default: 'ui/themes/alchemy-rose/cursors/default.svg',
          pointer: 'ui/themes/alchemy-rose/cursors/pointer.svg',
        },
        icons: {
          close: 'ui/themes/alchemy-rose/icons/close.svg',
          voiceReplay: 'ui/themes/alchemy-rose/icons/voice-replay.svg',
        },
        buttonFamilies: {
          gameMenuButton: {
            normal: 'ui/themes/alchemy-rose/choices/choice-normal.svg',
            hover: 'ui/themes/alchemy-rose/choices/choice-hover.svg',
            pressed: 'ui/themes/alchemy-rose/choices/choice-pressed.svg',
          },
          qab: {
            normal: 'ui/themes/alchemy-rose/choices/choice-normal.svg',
            hover: 'ui/themes/alchemy-rose/choices/choice-hover.svg',
            pressed: 'ui/themes/alchemy-rose/choices/choice-pressed.svg',
          },
          closeButton: {
            normal: 'ui/themes/alchemy-rose/choices/choice-normal.svg',
            hover: 'ui/themes/alchemy-rose/choices/choice-hover.svg',
            pressed: 'ui/themes/alchemy-rose/choices/choice-pressed.svg',
          },
          pageTabPager: {
            normal: 'ui/themes/alchemy-rose/choices/choice-normal.svg',
            hover: 'ui/themes/alchemy-rose/choices/choice-hover.svg',
            pressed: 'ui/themes/alchemy-rose/choices/choice-pressed.svg',
            selected: 'ui/themes/alchemy-rose/choices/choice-selected.svg',
          },
          settingsTab: {
            normal: 'ui/themes/alchemy-rose/choices/choice-normal.svg',
            hover: 'ui/themes/alchemy-rose/choices/choice-hover.svg',
            pressed: 'ui/themes/alchemy-rose/choices/choice-pressed.svg',
            selected: 'ui/themes/alchemy-rose/choices/choice-selected.svg',
          },
        },
      },
      widgetStyles: {
        tab: {
          shape: 'ribbon',
          activeColor: 'rgba(184, 93, 121, 0.88)',
          inactiveColor: 'rgba(231, 183, 189, 0.14)',
          activeTextColor: '#FFF1F4',
          inactiveTextColor: 'rgba(255, 241, 244, 0.68)',
        },
        toggle: {
          style: 'pill',
          onColor: 'rgba(184, 93, 121, 0.88)',
          offColor: 'rgba(231, 183, 189, 0.16)',
          thumbColor: '#FFF1F4',
        },
        slider: {
          trackColor: 'rgba(231, 183, 189, 0.16)',
          fillColor: 'rgba(184, 93, 121, 0.84)',
          thumbColor: '#FFF1F4',
          thumbStyle: 'gem',
        },
        panel: {
          background: 'rgba(20, 9, 19, 0.88)',
          border: '1px solid rgba(217, 169, 148, 0.24)',
          borderRadius: 8,
          backdropBlur: 14,
        },
        button: {
          background: 'rgba(76, 32, 58, 0.62)',
          hoverBackground: 'rgba(138, 63, 96, 0.78)',
          activeBackground: 'rgba(184, 93, 121, 0.86)',
          textColor: 'rgba(255, 241, 244, 0.94)',
          borderRadius: 6,
          border: '1px solid rgba(231, 183, 189, 0.26)',
        },
      },
      dialogueBox: {
        layout: 'ornate-lower-third',
        nameplateStyle: 'inline',
        nameplateBackgroundImage: 'ui/themes/alchemy-rose/dialogue/nameplate.svg',
        background: 'rgba(18, 8, 18, 0.92)',
        border: '1px solid rgba(217, 169, 148, 0.28)',
        shadow: '0 18px 46px rgba(5, 2, 8, 0.42)',
        decorations: [
          {
            src: 'ui/themes/alchemy-rose/dialogue/corner-ornament.svg',
            x: 30,
            y: 108,
            width: 72,
            height: 72,
            opacity: 0.30,
          },
          {
            src: 'ui/themes/alchemy-rose/dialogue/corner-ornament.svg',
            x: 1178,
            y: 108,
            width: 72,
            height: 72,
            rotation: 90,
            opacity: 0.30,
          },
        ],
      },
      saveLoadScreen: {
        header: {
          title: '存档 / 读档',
          saveTitleColor: 'rgba(255, 226, 231, 0.96)',
          loadTitleColor: 'rgba(231, 183, 189, 0.92)',
          accentBarColor: 'rgba(217, 169, 148, 0.86)',
        },
        slot: {
          background: 'rgba(58, 24, 48, 0.62)',
          borderRadius: 8,
          border: '1px solid rgba(217, 169, 148, 0.22)',
          emptyText: '空存档',
        },
        pagination: {
          style: 'dots',
          activeColor: 'rgba(231, 183, 189, 0.92)',
          inactiveColor: 'rgba(143, 211, 220, 0.28)',
        },
        chrome: {
          backgroundColor: 'rgba(20, 9, 19, 0.88)',
          backgroundImage: 'ui/themes/alchemy-rose/screens/chrome.svg',
          edgeGlow: 'rgba(231, 183, 189, 0.22)',
        },
      },
      backlogScreen: {
        header: {
          title: '回看记录',
          accentBarColor: 'rgba(217, 169, 148, 0.86)',
        },
        entry: {
          speakerColor: 'rgba(255, 226, 231, 0.96)',
          hoverBackground: 'rgba(138, 63, 96, 0.20)',
        },
        chrome: {
          backgroundColor: 'rgba(20, 9, 19, 0.88)',
          backgroundImage: 'ui/themes/alchemy-rose/screens/chrome.svg',
          dividerColor: 'rgba(217, 169, 148, 0.22)',
        },
      },
      gameMenu: {
        background: 'rgba(12, 6, 14, 0.76)',
        borderRadius: 8,
        backdropBlur: 16,
        buttons: {
          save: { label: '存档', icon: 'ui/themes/alchemy-rose/icons/save.svg' },
          load: { label: '读档', icon: 'ui/themes/alchemy-rose/icons/load.svg' },
          backlog: { label: '回忆', icon: 'ui/themes/alchemy-rose/icons/backlog.svg' },
          settings: { label: '设置', icon: 'ui/themes/alchemy-rose/icons/settings.svg' },
          title: { label: '标题', icon: 'ui/themes/alchemy-rose/icons/title.svg' },
          close: { label: '返回', icon: 'ui/themes/alchemy-rose/icons/close.svg' },
        },
        chrome: {
          backgroundColor: 'rgba(20, 9, 19, 0.88)',
          backgroundImage: 'ui/themes/alchemy-rose/screens/chrome.svg',
          edgeGlow: 'rgba(231, 183, 189, 0.22)',
        },
      },
      settingsScreen: {
        header: {
          title: { text: '系统设定', color: 'rgba(255, 226, 231, 0.96)' },
          subtitle: '炼金蔷薇 · 玫瑰金烟紫系统',
        },
        tabBar: {
          enabled: false,
        },
        footer: {
          height: 60,
          buttons: [
            { text: '恢复默认', action: 'reset', x: 1030, y: 14 },
          ],
        },
        chrome: {
          backgroundColor: 'rgba(20, 9, 19, 0.90)',
          backgroundImage: 'ui/themes/alchemy-rose/screens/chrome.svg',
          border: '1px solid rgba(217, 169, 148, 0.24)',
        },
      },
      titleScreen: {
        background: 'ui/themes/alchemy-rose/title/background.svg',
        elements: [
          {
            type: 'image',
            src: 'ui/themes/alchemy-rose/title/mark.svg',
            x: 640,
            y: 190,
            anchor: 'center',
            width: 600,
            height: 220,
          },
          {
            type: 'text',
            content: 'VISUAL NOVEL',
            x: 640,
            y: 318,
            anchor: 'center',
            fontSize: 18,
            fontFamily: "'Noto Serif SC', Georgia, serif",
            color: 'rgba(231, 183, 189, 0.88)',
            letterSpacing: 6,
            textShadow: '0 10px 30px rgba(5, 2, 8, 0.40)',
          },
          {
            type: 'button',
            text: '开始',
            action: 'start',
            x: 640,
            y: 412,
            anchor: 'center',
            width: 248,
            height: 56,
            fontSize: 20,
            fontFamily: "'Noto Serif SC', Georgia, serif",
            color: 'rgba(255, 241, 244, 0.96)',
            backgroundColor: 'rgba(76, 32, 58, 0.78)',
            hoverColor: 'rgba(138, 63, 96, 0.88)',
            borderRadius: 6,
            border: '1px solid rgba(231, 183, 189, 0.32)',
          },
          {
            type: 'button',
            text: '设置',
            action: 'settings',
            x: 640,
            y: 486,
            anchor: 'center',
            width: 248,
            height: 56,
            fontSize: 20,
            fontFamily: "'Noto Serif SC', Georgia, serif",
            color: 'rgba(255, 241, 244, 0.94)',
            backgroundColor: 'rgba(42, 18, 42, 0.76)',
            hoverColor: 'rgba(106, 45, 78, 0.86)',
            borderRadius: 6,
            border: '1px solid rgba(217, 169, 148, 0.28)',
          },
        ],
      },
    },
  }),
];
