/**
 * Built-in Theme Presets — 4 professional color schemes.
 *
 * Each preset contains a complete set of 41 design tokens matching
 * the DEFAULT_TOKENS vocabulary from tokens.js. Values use the same
 * formats: rgba(), linear-gradient(), font-family strings, and px units.
 *
 * Generated by tools/generatePresets.js using colorHarmony + contrast
 * modules, then hardcoded here for zero runtime overhead.
 *
 * @module engine/presets
 */

// ─── Theme Presets (D-04, D-05) ────────────────────────

/**
 * @typedef {Object} ThemePreset
 * @property {string} id — unique identifier
 * @property {string} name — Chinese display name
 * @property {string} description — Chinese description
 * @property {string} primaryColor — hex primary for card swatch accent
 * @property {Record<string, string>} tokens — all 41 token key/value pairs
 */

/** @type {ThemePreset[]} */
export const THEME_PRESETS = [
  {
    id: 'modern',
    name: '现代',
    description: '清新蓝色调，适合现代都市题材',
    primaryColor: '#4A90D9',
    tokens: {
      // ─── Core Colors ────────────────────────────────
      'primary': 'rgba(74, 143, 217, 0.90)',
      'primary-subtle': 'rgba(27, 38, 50, 0.08)',
      'danger': '#ff6b6b',
      'danger-hover': 'rgba(255, 100, 100, 0.90)',
      'accent': 'rgba(219, 155, 87, 0.25)',
      'accent-border': 'rgba(191, 130, 64, 0.50)',
      'shadow': 'rgba(46, 75, 107, 0.30)',
      'title-glow': 'rgba(83, 138, 198, 0.30)',
      'save-title': 'rgba(74, 143, 217, 0.90)',
      'load-title': 'rgba(224, 168, 108, 0.90)',

      // ─── Text ───────────────────────────────────────
      'text': 'rgba(242, 242, 243, 0.92)',
      'text-heading': 'rgba(228, 229, 231, 0.85)',
      'text-secondary': 'rgba(196, 199, 202, 0.75)',
      'text-muted': 'rgba(135, 140, 146, 0.50)',
      'text-dim': 'rgba(102, 107, 112, 0.40)',
      'text-faint': 'rgba(78, 81, 86, 0.30)',

      // ─── Borders ────────────────────────────────────
      'border': 'rgba(41, 51, 61, 0.08)',
      'border-hover': 'rgba(46, 112, 184, 0.30)',
      'border-active': 'rgba(66, 138, 215, 0.50)',

      // ─── Backgrounds ────────────────────────────────
      'dialogue-bg': 'linear-gradient(to top, rgba(11, 13, 15, 0.92) 0%, rgba(11, 13, 15, 0.88) 70%, rgba(11, 13, 15, 0.75) 100%)',
      'panel-bg': 'rgba(12, 15, 18, 0.95)',
      'menu-bg': 'rgba(9, 10, 11, 0.70)',
      'card-bg': 'rgba(23, 30, 38, 0.60)',
      'card-bg-hover': 'rgba(29, 40, 53, 0.60)',
      'title-bg': 'linear-gradient(135deg, rgb(14, 18, 21) 0%, rgb(16, 20, 24) 30%, rgb(15, 19, 23) 60%, rgb(14, 18, 21) 100%)',
      'confirm-bg': 'rgba(16, 20, 24, 0.95)',

      // ─── Buttons ────────────────────────────────────
      'btn-bg': 'rgba(38, 63, 89, 0.60)',
      'btn-text': 'rgba(234, 235, 236, 0.90)',
      'btn-border': 'rgba(48, 56, 65, 0.10)',
      'btn-hover-bg': 'rgba(40, 88, 138, 0.70)',
      'btn-hover-text': 'rgba(244, 245, 245, 0.95)',
      'btn-hover-border': 'rgba(46, 112, 184, 0.30)',

      // ─── Fonts ──────────────────────────────────────
      'font-body': "'Noto Sans SC', 'Segoe UI', 'Microsoft YaHei', sans-serif",
      'font-display': "'Noto Serif SC', serif",

      // ─── Radii ──────────────────────────────────────
      'radius': '4px',
      'radius-lg': '6px',

      // ─── Blur ───────────────────────────────────────
      'blur': '8px',

      // ─── Controls ───────────────────────────────────
      'slider-track': 'rgba(34, 38, 42, 0.10)',
      'slider-thumb': 'rgba(108, 164, 224, 0.80)',
      'scrollbar': 'rgba(34, 38, 42, 0.10)',

      // ─── Speaker ────────────────────────────────────
      'speaker-shadow': 'rgba(135, 140, 146, 0.20)',
    },
  },
  {
    id: 'japanese',
    name: '和风',
    description: '温暖大地色调，适合日本传统题材',
    primaryColor: '#C8A882',
    tokens: {
      // ─── Core Colors ────────────────────────────────
      'primary': 'rgba(201, 134, 131, 0.90)',
      'primary-subtle': 'rgba(50, 28, 27, 0.08)',
      'danger': '#ff6b6b',
      'danger-hover': 'rgba(255, 100, 100, 0.90)',
      'accent': 'rgba(193, 157, 113, 0.25)',
      'accent-border': 'rgba(177, 132, 78, 0.50)',
      'shadow': 'rgba(106, 50, 47, 0.30)',
      'title-glow': 'rgba(185, 100, 95, 0.30)',
      'save-title': 'rgba(201, 134, 131, 0.90)',
      'load-title': 'rgba(201, 169, 131, 0.90)',

      // ─── Text ───────────────────────────────────────
      'text': 'rgba(243, 242, 242, 0.92)',
      'text-heading': 'rgba(231, 228, 228, 0.85)',
      'text-secondary': 'rgba(202, 196, 196, 0.75)',
      'text-muted': 'rgba(146, 135, 135, 0.50)',
      'text-dim': 'rgba(112, 102, 102, 0.40)',
      'text-faint': 'rgba(86, 78, 78, 0.30)',

      // ─── Borders ────────────────────────────────────
      'border': 'rgba(61, 42, 41, 0.08)',
      'border-hover': 'rgba(160, 74, 70, 0.30)',
      'border-active': 'rgba(185, 100, 95, 0.50)',

      // ─── Backgrounds ────────────────────────────────
      'dialogue-bg': 'linear-gradient(to top, rgba(15, 11, 11, 0.92) 0%, rgba(15, 11, 11, 0.88) 70%, rgba(15, 11, 11, 0.75) 100%)',
      'panel-bg': 'rgba(18, 13, 12, 0.95)',
      'menu-bg': 'rgba(11, 9, 9, 0.70)',
      'card-bg': 'rgba(38, 24, 23, 0.60)',
      'card-bg-hover': 'rgba(53, 30, 29, 0.60)',
      'title-bg': 'linear-gradient(135deg, rgb(21, 15, 14) 0%, rgb(24, 17, 16) 30%, rgb(23, 16, 15) 60%, rgb(21, 15, 14) 100%)',
      'confirm-bg': 'rgba(24, 17, 16, 0.95)',

      // ─── Buttons ────────────────────────────────────
      'btn-bg': 'rgba(89, 41, 39, 0.60)',
      'btn-text': 'rgba(236, 234, 234, 0.90)',
      'btn-border': 'rgba(65, 49, 48, 0.10)',
      'btn-hover-bg': 'rgba(124, 58, 54, 0.70)',
      'btn-hover-text': 'rgba(245, 244, 244, 0.95)',
      'btn-hover-border': 'rgba(160, 74, 70, 0.30)',

      // ─── Fonts ──────────────────────────────────────
      'font-body': "'Noto Sans SC', 'Segoe UI', 'Microsoft YaHei', sans-serif",
      'font-display': "'Noto Serif SC', serif",

      // ─── Radii ──────────────────────────────────────
      'radius': '2px',
      'radius-lg': '4px',

      // ─── Blur ───────────────────────────────────────
      'blur': '8px',

      // ─── Controls ───────────────────────────────────
      'slider-track': 'rgba(42, 35, 34, 0.10)',
      'slider-thumb': 'rgba(201, 134, 131, 0.80)',
      'scrollbar': 'rgba(42, 35, 34, 0.10)',

      // ─── Speaker ────────────────────────────────────
      'speaker-shadow': 'rgba(146, 135, 135, 0.20)',
    },
  },
  {
    id: 'fantasy',
    name: '幻想',
    description: '神秘紫色调，适合奇幻冒险题材',
    primaryColor: '#7B2FBE',
    tokens: {
      // ─── Core Colors ────────────────────────────────
      'primary': 'rgba(145, 71, 209, 0.90)',
      'primary-subtle': 'rgba(39, 27, 50, 0.08)',
      'danger': '#ff6b6b',
      'danger-hover': 'rgba(255, 100, 100, 0.90)',
      'accent': 'rgba(214, 157, 92, 0.25)',
      'accent-border': 'rgba(191, 132, 64, 0.50)',
      'shadow': 'rgba(79, 46, 107, 0.30)',
      'title-glow': 'rgba(144, 83, 198, 0.30)',
      'save-title': 'rgba(145, 71, 209, 0.90)',
      'load-title': 'rgba(219, 169, 112, 0.90)',

      // ─── Text ───────────────────────────────────────
      'text': 'rgba(242, 242, 243, 0.92)',
      'text-heading': 'rgba(230, 228, 231, 0.85)',
      'text-secondary': 'rgba(199, 196, 202, 0.75)',
      'text-muted': 'rgba(141, 135, 146, 0.50)',
      'text-dim': 'rgba(107, 102, 112, 0.40)',
      'text-faint': 'rgba(82, 78, 86, 0.30)',

      // ─── Borders ────────────────────────────────────
      'border': 'rgba(52, 41, 61, 0.08)',
      'border-hover': 'rgba(119, 46, 184, 0.30)',
      'border-active': 'rgba(145, 71, 209, 0.50)',

      // ─── Backgrounds ────────────────────────────────
      'dialogue-bg': 'linear-gradient(to top, rgba(13, 11, 15, 0.92) 0%, rgba(13, 11, 15, 0.88) 70%, rgba(13, 11, 15, 0.75) 100%)',
      'panel-bg': 'rgba(16, 12, 18, 0.95)',
      'menu-bg': 'rgba(10, 9, 11, 0.70)',
      'card-bg': 'rgba(31, 23, 38, 0.60)',
      'card-bg-hover': 'rgba(42, 29, 53, 0.60)',
      'title-bg': 'linear-gradient(135deg, rgb(18, 14, 21) 0%, rgb(21, 16, 24) 30%, rgb(20, 15, 23) 60%, rgb(18, 14, 21) 100%)',
      'confirm-bg': 'rgba(21, 16, 24, 0.95)',

      // ─── Buttons ────────────────────────────────────
      'btn-bg': 'rgba(65, 38, 89, 0.60)',
      'btn-text': 'rgba(235, 234, 236, 0.90)',
      'btn-border': 'rgba(57, 48, 65, 0.10)',
      'btn-hover-bg': 'rgba(93, 40, 138, 0.70)',
      'btn-hover-text': 'rgba(245, 244, 245, 0.95)',
      'btn-hover-border': 'rgba(119, 46, 184, 0.30)',

      // ─── Fonts ──────────────────────────────────────
      'font-body': "'Noto Sans SC', 'Segoe UI', 'Microsoft YaHei', sans-serif",
      'font-display': "'Noto Serif SC', serif",

      // ─── Radii ──────────────────────────────────────
      'radius': '6px',
      'radius-lg': '8px',

      // ─── Blur ───────────────────────────────────────
      'blur': '8px',

      // ─── Controls ───────────────────────────────────
      'slider-track': 'rgba(39, 34, 42, 0.10)',
      'slider-thumb': 'rgba(169, 112, 219, 0.80)',
      'scrollbar': 'rgba(39, 34, 42, 0.10)',

      // ─── Speaker ────────────────────────────────────
      'speaker-shadow': 'rgba(141, 135, 146, 0.20)',
    },
  },
  {
    id: 'minimal',
    name: '简约',
    description: '低饱和度灰色调，适合简洁现代题材',
    primaryColor: '#333333',
    tokens: {
      // ─── Core Colors ────────────────────────────────
      'primary': 'rgba(140, 140, 140, 0.90)',
      'primary-subtle': 'rgba(38, 38, 38, 0.08)',
      'danger': '#ff6b6b',
      'danger-hover': 'rgba(255, 100, 100, 0.90)',
      'accent': 'rgba(153, 153, 153, 0.25)',
      'accent-border': 'rgba(128, 128, 128, 0.50)',
      'shadow': 'rgba(77, 77, 77, 0.30)',
      'title-glow': 'rgba(140, 140, 140, 0.30)',
      'save-title': 'rgba(140, 140, 140, 0.90)',
      'load-title': 'rgba(166, 166, 166, 0.90)',

      // ─── Text ───────────────────────────────────────
      'text': 'rgba(243, 242, 242, 0.92)',
      'text-heading': 'rgba(231, 228, 228, 0.85)',
      'text-secondary': 'rgba(202, 196, 196, 0.75)',
      'text-muted': 'rgba(146, 135, 135, 0.50)',
      'text-dim': 'rgba(112, 102, 102, 0.40)',
      'text-faint': 'rgba(86, 78, 78, 0.30)',

      // ─── Borders ────────────────────────────────────
      'border': 'rgba(51, 51, 51, 0.08)',
      'border-hover': 'rgba(115, 115, 115, 0.30)',
      'border-active': 'rgba(140, 140, 140, 0.50)',

      // ─── Backgrounds ────────────────────────────────
      'dialogue-bg': 'linear-gradient(to top, rgba(13, 13, 13, 0.92) 0%, rgba(13, 13, 13, 0.88) 70%, rgba(13, 13, 13, 0.75) 100%)',
      'panel-bg': 'rgba(15, 15, 15, 0.95)',
      'menu-bg': 'rgba(10, 10, 10, 0.70)',
      'card-bg': 'rgba(31, 31, 31, 0.60)',
      'card-bg-hover': 'rgba(41, 41, 41, 0.60)',
      'title-bg': 'linear-gradient(135deg, rgb(18, 18, 18) 0%, rgb(20, 20, 20) 30%, rgb(19, 19, 19) 60%, rgb(18, 18, 18) 100%)',
      'confirm-bg': 'rgba(20, 20, 20, 0.95)',

      // ─── Buttons ────────────────────────────────────
      'btn-bg': 'rgba(64, 64, 64, 0.60)',
      'btn-text': 'rgba(236, 234, 234, 0.90)',
      'btn-border': 'rgba(56, 56, 56, 0.10)',
      'btn-hover-bg': 'rgba(89, 89, 89, 0.70)',
      'btn-hover-text': 'rgba(245, 244, 244, 0.95)',
      'btn-hover-border': 'rgba(115, 115, 115, 0.30)',

      // ─── Fonts ──────────────────────────────────────
      'font-body': "'Noto Sans SC', 'Segoe UI', 'Microsoft YaHei', sans-serif",
      'font-display': "'Noto Serif SC', serif",

      // ─── Radii ──────────────────────────────────────
      'radius': '4px',
      'radius-lg': '6px',

      // ─── Blur ───────────────────────────────────────
      'blur': '8px',

      // ─── Controls ───────────────────────────────────
      'slider-track': 'rgba(38, 38, 38, 0.10)',
      'slider-thumb': 'rgba(166, 166, 166, 0.80)',
      'scrollbar': 'rgba(38, 38, 38, 0.10)',

      // ─── Speaker ────────────────────────────────────
      'speaker-shadow': 'rgba(146, 135, 135, 0.20)',
    },
  },
];
